BuidlGuidl/abi.ninja

packages/react-app/src/components/Contract/index.jsx, packages/react-app/src/styles/_contract.less
Thanks so much for making such an awesome tool !! 
I noticed that the styling for Settings Modal looks different than the whole theme of the app, just updated it to match the overall theme. 
Before         |  After
:-----------:|:-------------------------------------------------------:
https://user-images.githubusercontent.com/80153681/197357562-17309c11-7022-4169-9372-495e48c40342.mp4
please let me know if there are any changes or if something can be improved, be it css `class` naming convention or nesting of styles in `_contract.less` anything would love to improve it  🙌
=> update settings modal styles to match theme

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx, packages/nextjs/pages/[contractAddress]/[network].tsx, packages/nextjs/pages/index.tsx, packages/nextjs/utils/abi.ts
Working on this draft to fetch abi from AnyABI API, to not have to deal with Etherscan API limits. 
Current Etherscan abi fetch stays as fallback option in case AnyABI fails to fetch the abi.
In https://github.com/BuidlGuidl/abi.ninja/pull/35/commits/c8b4af94e84f398ee21c647cdde43358fb4e7504 I've also added the abi load into the global state. The reasoning behind it was that we were already fetching Etherscan API to know if the abi was available, so with that change we save a fetch in ContractDetailPage, but probably duplicating the code in both pages isn't the way to go, let me know what do you think 🙌
Closes #26
=> Fetch abi from AnyABI as first source and leave Etherscan as fallback

packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
The «footer» was appearing in a weird position on some resolutions. It was because the `menu` class has flex wrap on. Hope I'm not breaking anything :D
Before:
After:
=> Fix wrong footer position on some resolutions

packages/nextjs/package.json, yarn.lock
Fixes #45, Actually it seems there was some bug in next 13.1 which was not processing  daisUI > 3.0  css during build updating next to latest should solve this as it was suggested here https://github.com/saadeghi/daisyui/issues/2303
Also didn't updated to latest / next 13.4 just to be safe since I heard there were some wierd issues faced by people using pages router when they introduced app router stable (although their docs says it is backward compatible with pages router)
=> use next 13.3.4

packages/nextjs/components/scaffold-eth/Contract/ContractReadMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractWriteMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx
A couple of small tweaks:
- #50 
- Feedback messages when there were no Read/Write methods selected was a bit too heavy.
Before: ![image](https://github.com/BuidlGuidl/abi.ninja/assets/55535804/c2e5524f-4e8e-4106-a640-c4dcbeb19198)
After: 
Read button after fix:
=> Fix read button placement and lower weight of empty methods messages

packages/nextjs/components/scaffold-eth/Contract/ContractInput.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractReadMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractWriteMethods.tsx, packages/nextjs/components/scaffold-eth/Contract/DisplayVariable.tsx, packages/nextjs/components/scaffold-eth/Contract/MethodSelector.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx
- Fixes #54 
- Fix zero inputs send button positioning (was overlaping close icon)
> Copy button doesn't have hover effect (minor)
Haven't fixed this one because I think it means changing `<Address>` component. Can add it a `hover:opacity-70` effect, but maybe we should do it in SE-2 then.
If you find any other style issue, lmk to fix! 🙌♥
=> Fix style issues in Contract detail page

.github/pull_request_template.md, CONTRIBUTING.md, README.md
This PR aims to update the Scaffold-ETH references from the Contribution Guide to Abi Ninja, and update Readme contribution paragraph. 
Another approach would be to keep the Readme as it is right now (with the link to SE-2 Contribution Guide), and just delete CONTRIBUTING.MD from this repo. LMK if you just prefer this option 🙌
Closes #56
=> Update contributing guide to adapt it for Abi Ninja

packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/pages/[contractAddress]/[network].tsx
Currently users can manually set their url to open the ContractDetail page for their desired contract, by typing `/{contractAddress}/{chainId}` => for example gitcoin in mainnet: `/0xde30da39c46104798bb5aa3fe8b9e0e1f348163f/1`
This PR adds the possibility of using {chainName} or {chainId} indistinctly, so it's easier for most users to create their URLs manually => Using {chainName} for the same example:  `/0xde30da39c46104798bb5aa3fe8b9e0e1f348163f/mainnet`
__Some considerations__
- In this initial approach I'm comparing the network name from the URL with `chain.network` from `viem/chains`, but I've realized some networks got a weird `chain.network` (mainnet for example), I solved it with this hacky code: 
`if (normalizedNetwork === "ethereum" || normalizedNetwork === "mainnet") { …
=> Add logic to parse network name from URL

packages/nextjs/components/scaffold-eth/Contract/ContractInput.tsx, packages/nextjs/components/scaffold-eth/Contract/ReadOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/Tuple.tsx, packages/nextjs/components/scaffold-eth/Contract/TupleArray.tsx, packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx, packages/nextjs/utils/scaffold-eth/contract.ts
Demo : 
https://github.com/BuidlGuidl/abi.ninja/assets/80153681/3500a484-225b-43f3-8d7b-345ff84f8c66
Here is example [opensea contract](https://etherscan.io/address/0x00000000006c3852cbEf3e08E8dF289169EdE581#code) address on mainnet : 0x00000000006c3852cbEf3e08E8dF289169EdE581
Please feel free to push / suggest style improvement & maybe we could also create issue for better styles on keep iterating their if this feels good for inital version 🙌
=> Improve structs UI 

packages/nextjs/middleware.ts
Didn't use `next.config.js` [approach](https://nextjs.org/docs/pages/building-your-application/routing/redirecting#redirects-in-nextconfigjs) of redirecting instead used [middleware](https://nextjs.org/docs/app/building-your-application/routing/middleware) approach since : 
1. The path params are attached direclty to base url eg: `locahost:3000/[contractAddress]` it would have been easy to match if it was `localhost:3000/contract/[contractAddress]`
2. Also wanted to add address regex logic 
Closes #67
=> add middlware to redirect /[contractAddress] requests to mainnet by default

packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx
This PR:
- Adds uids only to the overloaded functions, keeping the others same as their name, thus enables the url to be shorter
- Moves the augmentMethodsWithUid function out of the component to make things cleaner
[as suggested by Shiv](https://github.com/BuidlGuidl/abi.ninja/pull/70#issuecomment-1994535611).
Thanks for the idea @technophile-04 !
Please be nitpicky and rude if you are reviewing this PR!
https://github.com/BuidlGuidl/abi.ninja/assets/108868128/7af1bb3a-f620-43be-b5d4-6a78110a2964
https://github.com/BuidlGuidl/abi.ninja/assets/108868128/d7b38f10-8258-42fd-b9fd-e4a95e9c0bb3
_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is …
=> Only add uids to overloaded methods

packages/nextjs/components/MiniFooter.tsx, packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/pages/[contractAddress]/[network].tsx, packages/nextjs/pages/_app.tsx, packages/nextjs/pages/index.tsx
In some resolutions, the mini footer is unclickable due to the og footer coming on top of it.
https://github.com/BuidlGuidl/abi.ninja/assets/108868128/afba4131-5efa-481f-9d37-6c52ebe3e535
https://github.com/BuidlGuidl/abi.ninja/assets/108868128/f267d8ce-3742-429e-818a-0f20eaaf947e
=> Remove extra footer

packages/nextjs/pages/[contractAddress]/[network].tsx, packages/nextjs/pages/index.tsx
Pass undefined to AlchemyProvider in both index.tsx and [network].tsx files to prevent the page from crashing.
I have another issue + PR coming up about this, and I fixed this problem by adapting the code to use viem instead of ethers which is more up-to-date in terms of networks and easier to implement. Also added support for Zora contracts, will open an issue as soon as it is ready. 
Tried to provide a remedy as quickly as possible in this PR.
Please see #79 
_Closes #79 _
=> Pass undefined to AlchemyProvider

packages/nextjs/pages/[contractAddress]/[network].tsx, packages/nextjs/pages/index.tsx
We recently merged #80, it was a quick fix but maybe instead of relying on ethers for alchemy provider (which has very limited providers) we rely on general JsonRpcProvider and get the alchemy link from viem chains. 
Also updated the logic a bit so now we only check for proxy contracts if we have viem's alchemy link for that chain
=> allow more networks for proxy contracts

packages/nextjs/package.json, packages/nextjs/pages/[contractAddress]/[network].tsx, packages/nextjs/pages/index.tsx, packages/nextjs/utils/abi-ninja/proxyContracts.ts, yarn.lock
This PR:
- Migrates the proxy detection logic that we currently use from evm-proxy-detection to viem
- Adds the ability to detect Zora contracts by first checking for EIP-1967
There still might be some rough edges on this PR so feel free to give me some harsh feedback! It helps more that way!
=> Use viem for detecting proxy contracts logic

packages/nextjs/scaffold.config.ts
This gives an error when people try to connect through the mobile rainbow wallet : 
Maybe we can allow lccal network again we migrate to wagmi v2 : https://x.com/rainbowdotme/status/1779930443397337534?s=46&t=3J-S7_iZrqdWSB0sUNFYRA
=> remove localnetwork for now

README.md
Adding last features to Readme and some tweaks. Main changes:
- List all kind of contracts we support
- Adapt homepage screenshot and add unverified option screenshot. (LMK if you like that 1 row/2column view, or if you prefer regular screenshots in two different rows)
- Showcase complex struct with screenshot
This PR should only be merged after #71 and #72. Can adapt it in case we see one of the PRs is going to be delayed some time.
=> Adapt Readme to heimdall and proxies version

packages/nextjs/utils/scaffold-eth/networks.ts
We don't see this on local but in prod the zksync img is not shown. This lead me into thinking that the case is the problem here.
=> Hotfix: change zkSync to zksync in networks.ts

packages/nextjs/components/NetworksDropdown.tsx, packages/nextjs/pages/index.tsx
Adds a skeleton loader for networks.
I set the height to exactly 38 pixels because that is the size that `react-select` has the select menu set at. I'm not sure if this is the best approach, but I think it works.
_Closes #98_
Your ENS/address: `byteatatime.eth`
=> Add skeleton loader when loading networks + Resize abi ninja logo

packages/nextjs/utils/abi.ts
Some blockexplorers doesn't require any api key for example ZkSync, so this PR relaxes the apiKey check which we had earlier 
Fixes #110
=> relax etherscan apiKey constrain

packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx, packages/nextjs/tailwind.config.js
Adds a tooltip-info color to the tooltip div. 
Also added some shadow to make it stand out more in light theme
<p align="center">
<b>Before</b><br>
</p>
<p align="center">
<b>After</b><br>
</p>
_Closes #122 
=> Add tooltip-info and shadow-lg to the tooltip div

packages/nextjs/components/scaffold-eth/Contract/utilsContract.tsx
Fixes #134 
Just migrated the fix we did for SE-2 in these PRs:
https://github.com/scaffold-eth/scaffold-eth-2/pull/893
https://github.com/scaffold-eth/scaffold-eth-2/pull/894
=> Fixes BigInt parsing losing precision in IntegerInput

packages/nextjs/pages/index.tsx
Uses the new url structure and can use https://heimdall-api-v2.fly.dev/ as an env var.
The new url is already added as an env var to the project at vercel.
It is live at: https://abi-ninja-v2-ewpdbpx46-buidlguidldao.vercel.app/
_Closes #133 
=> Update heimdall backend url

packages/nextjs/cypress/e2e/contract_interaction.cy.ts, packages/nextjs/cypress/support/commands.ts
- Changes the way that the networks are selected from the dropdown:
Instead of clicking on the dropdown and looking for a something with `[role="option"]`, we click on the dropdown menu, start typing the network name, and click on the first result that appears:
`cy.get("#react-select-container")
.click()
.find("input")
.first()
.type(networkName, { force: true })
.type("{enter}", { force: true });`
- Changes the way Custom chains dropdown entry is selected to the method above
- Removes the 1000 ms delay on the proxy contract on Base test 
I have tested these changes at least 50 times on my local instance but cypress may behave differently on gh actions
Fixes #146
=> Type to find networks instead of choosing them by role="option" in cypress tests

packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/NetworkOptions.tsx, packages/nextjs/hooks/scaffold-eth/useNetworkColor.ts
Removed useDarkMode leftovers after https://github.com/BuidlGuidl/abi.ninja/pull/93.
Related to https://github.com/scaffold-eth/scaffold-eth-2/pull/707.
_#91_
=> Fix detecting dark theme leftovers

packages/nextjs/utils/abi-ninja/proxyContracts.ts
This PR adds support for detecting OpenZeppelin proxies by uncommenting and implementing the OpenZeppelin implementation slot detection logic in the `detectProxyTarget` function.
Changes made:
1. Uncommented the `OPEN_ZEPPELIN_IMPLEMENTATION_SLOT` constant.
2. Added a new `detectUsingOpenZeppelinSlot` function to check for OpenZeppelin proxies.
3. Included the new detection method in the primary detection methods array.
Fixes #154 
Your ENS/address: portdev.eth
=> Fix open zeppelin proxy detection

packages/nextjs/components/scaffold-eth/Contract/WriteOnlyFunctionForm.tsx, packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx, packages/nextjs/components/scaffold-eth/Input/utils.ts
Related to https://github.com/BuidlGuidl/abi.ninja/pull/135
https://abi.ninja/0xde30da39c46104798bb5aa3fe8b9e0e1f348163f/1?methods=transfer
|  |  |
| --- | --- |
| ![abi ninja_0xde30da39c46104798bb5aa3fe8b9e0e1f348163f_1_methods=transfer](https://github.com/user-attachments/assets/cf08f9bb-82d3-4579-99c9-07989a3e5bde) | ![abi ninja_0xde30da39c46104798bb5aa3fe8b9e0e1f348163f_1_methods=transfer (1)](https://github.com/user-attachments/assets/7a8f59d7-b596-4f2e-81eb-d63e8ad2670c) |
_Concise description of proposed changes, We recommend using screenshots and videos for better description_
_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is …
=> Fix rounding issue when converting to wei

packages/nextjs/components/scaffold-eth/Contract/ContractUI.tsx, packages/nextjs/hooks/useFetchContractCreationInfo.ts
This PR adds the ability to view contract creation information and link to the creation transaction on block explorers.
-> Adds contract creation information display in the Contract Overview section
-> Integrates with Etherscan API v2 to fetch contract creation data
-> Adds clickable link to view the contract creation transaction on block explorers
=> Show contract creation information in the Contract Overview card
